version: '3.1'
services:
  action-runner:
    image: action-runner
    container_name: action-runner
    volumes:
      - ~/tmp/action-runner/app:/app
      - ~/tmp/action-runner/ActionRunnerPlaybooks:/playbooks
    ports:
      - 7032:7032
    restart: unless-stopped