version: '3.1'
services:
  action-runner:
    image: awlsring/action-runner:latest
    container_name: action-runner
    volumes:
      - /action-runner/app:/app
      - /action-runner/playbooks:/playbooks
    ports:
      - 7032:7032
    restart: unless-stopped